<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2Q9SV7O" name="Default test" tests="1" failures="1" timestamp="7 Nov 2018 21:29:39 GMT" time="37.058" errors="0">
  <testcase name="feature" time="36.363" classname="com.bdd.BDDFundTransfer.RunCukesTestBDD">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: bug beee expected [Transfer failed!! &amp;apos;John&amp;apos; is not approved. Please contact your branch)] but found [Transfer failed!! &amp;apos;John&amp;apos; is not approved. Please contact your branch]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: bug beee expected [Transfer failed!! 'John' is not approved. Please contact your branch)] but found [Transfer failed!! 'John' is not approved. Please contact your branch]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.AssertionError: bug beee expected [Transfer failed!! 'John' is not approved. Please contact your branch)] but found [Transfer failed!! 'John' is not approved. Please contact your branch]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.bdd.BDDFundTransfer.FundTransferStepDef.ensure_a_transaction_failure_message_is_displayed(FundTransferStepDef.java:65)
	at âœ½.Then ensure a transaction failure message "Transfer failed!! 'John' is not approved. Please contact your branch)" is displayed(fundtransfer.feature:26)
]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Default test -->
